config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => '/attachinary'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :posts do
    resources :comments, only: :create
  end
  authenticated :user do
    root to: "posts#index", as: "authenticated_user"
  end
  root to: "pages#landing"
  get "features" => "pages#features"
  get "landing" => "pages#landing"

  resources :users, only: [:show]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :text, presence: true, allow_blank: false
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_attachment :image
  belongs_to :user
  has_many :comments
  paginates_per 10
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  validates :name, presence: true
  has_many :posts
  has_many :comments

  def recent_posts
    posts.order(id: :desc).limit(10)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!

  def create
    comment = Comment.new(comment_params)
    comment.post = Post.find(params[:post_id])
    comment.user = current_user
    comment.save!

    redirect_to comment.post
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def features
  end

  def landing
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @posts = Post.order(id: :desc).page params[:page]
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post=Post.create(post_params)
    @post.user = current_user
      @post.save
    redirect_to posts_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def post_params
    params.require(:post).permit!
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
        redirect_to posts_path
    else
        render 'edit'
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Azi tu Mâine Eu</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= cloudinary_js_config %>  
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>
<body>

<%= render "shared/navbar" %>
<%= yield %>

</body>
</html>

app/views/pages/features.html.erb
<h1>Hello, these are my features!</h1>

app/views/pages/landing.html.erb
    <!-- Header -->
    <a name="about"></a>
    <div class="intro-header">
        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1>Viață nouă obiectelor vechi</h1>
                        <h3>Azi tu, Mâine eu e o comunitate de oameni care dau și primesc în dar lucruri.</h3>
                        <hr class="intro-divider">
                        <ul class="list-inline intro-social-buttons">
                            <li>
                                <%= link_to("Înregistrează-te", new_user_registration_path, class: "btn-default btn") %>
                            </li>
                            <li>
                                <%= link_to("Află mai multe", features_path, class: "btn-default btn") %>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->

    <!-- Page Content -->

  <a  name="services"></a>
    <div class="content-section-a">

        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Death to the Stock Photo:<br>Special Thanks</h2>
                    <p class="lead">A special thanks to <a target="_blank" href="http://join.deathtothestockphoto.com/">Death to the Stock Photo</a> for providing the photographs that you see in this template. Visit their website to become a member.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <%= image_tag "img/ipad.png", class: "img-responsive" %>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <div class="content-section-b">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">3D Device Mockups<br>by PSDCovers</h2>
                    <p class="lead">Turn your 2D designs into high quality, 3D product shots in seconds using free Photoshop actions by <a target="_blank" href="http://www.psdcovers.com/">PSDCovers</a>! Visit their website to download some of their awesome, free photoshop actions!</p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                    <%= image_tag "img/dog.png", class: "img-responsive" %>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-b -->

    <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Google Web Fonts and<br>Font Awesome Icons</h2>
                    <p class="lead">This template features the 'Lato' font, part of the <a target="_blank" href="http://www.google.com/fonts">Google Web Font library</a>, as well as <a target="_blank" href="http://fontawesome.io">icons from Font Awesome</a>.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <%= image_tag "img/phones.png", class: "img-responsive" %>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

  <a  name="contact"></a>
    <div class="banner">

        <div class="container">

            <div class="row">
                <div class="col-lg-6">
                    <h2>Connect to Start Bootstrap:</h2>
                </div>
                <div class="col-lg-6">
                    <ul class="list-inline banner-social-buttons">
                        <li>
                            <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                        </li>
                        <li>
                            <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                        </li>
                        <li>
                            <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                        </li>
                    </ul>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.banner -->

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <a href="#">Home</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#about">About</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#services">Services</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#contact">Contact</a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; Your Company 2014. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>

app/views/posts/_post.html.erb
<div class="item">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h5><%= link_to post.title, post %></h5>
    </div>
    <div class="panel-body">
      <%= cl_image_tag(post.image.path, width: 500, class: 'img-responsive img-thumbnail') %>
      <p>
        <%= post.body %>
      </p>
    </div>
    <div class="panel-footer">
<span class="label label-default">
  <%= link_to post.user.name, user_path(post.user) %>
</span>
      <% if current_user == post.user %>
        <%= link_to(post_path(post), method: :delete, class: 'btn btn-danger btn-xs pull-right') do %>
          <span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Delete
        <% end %>
        <%= link_to(edit_post_path(post), class: 'btn btn-default btn-xs pull-right') do %>
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= simple_form_for @post do |f| %>
  <%=f.text_field :link %>
  <%=f.submit %>  
<% end %>

app/views/posts/index.html.erb
<div class="container">  
  <div class="collection">
    <%= render @posts %>
  </div>
  <div class="pagination-container">
    <%= paginate @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="col-lg-4">
    <h1>Postare nouă</h1>  

    <%= simple_form_for @post do |form| %>  
      <%= form.input :title, :placeholder => "Dă-i un titlu bun", :label => "Titlu"  %>  
      <%= form.input :body, :placeholder => "Descriere", :label => "Descriere" %>
      <%= form.input :image, as: :attachinary, :label => "Imagine" %>
      <%= form.button :submit, "Creează postarea" %>  
    <% end %>  
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
<div class="row">
<div class="col-xs-12 col-md-8 col-md-offset-2">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h5><%= @post.title %></h5>
    </div>
    <div class="panel-body">
      <%= cl_image_tag(@post.image.path, class: 'img-responsive img-thumbnail') %>
      <p>
        <%= @post.body %>
      </p>
    </div>
    <div class="panel-footer">
      <span class="label label-default">
        <%= link_to @post.user.name, user_path(@post.user) %>
      </span>
      <% if current_user == @post.user %>
        <%= link_to(post_path(@post), method: :delete, class: 'btn btn-danger btn-xs pull-right') do %>
          <span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Delete
        <% end %>
        <%= link_to(edit_post_path(@post), class: 'btn btn-default btn-xs pull-right') do %>
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit
        <% end %>
      <% end %>
    </div>
  </div>

  <% @post.comments.each do |c| %>
    <div class="panel panel-default">
      <div class="panel-body">
        <p><%= c.text %></p>
        <em>By <%= link_to c.user.name, user_path(c.user) %></em>
      </div>
    </div>
  <% end %>

  <%= simple_form_for [@post, Comment.new] do |f| %>
    <%= f.input :text, label: false, required: false %>
    <%= f.button :submit, 'Comentează' %>
  <% end %>
</div>
</div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Azi tu Mâine eu", root_path, class: "navbar-brand" %>
    </div>

    <div class="navbar-collapse">
      <ul class="nav navbar-nav">
        <li>
          <% if user_signed_in? %>
            <%= link_to("Postare nouă", new_post_path) %>
          <% end %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if user_signed_in? %>
            <%= link_to('Ieșire', destroy_user_session_path, :method => :delete) %>
          <% else %>
            <%= link_to('Înregistrare', new_user_registration_path) %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/users/show.html.erb
<div class="container">
  <h1>
    <%= @user.name %>
  </h1>

  <h6>Latest posts:</h6>
  <div class="collection">
    <%= render @user.recent_posts %>
  </div>
</div>